[package]
name = "rust_ownership"
version = "0.1.0"
authors = ["Jerin George <jerin.g@grinntech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
